name: Hassfest
on:
  push:
  pull_request:
jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
